### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by nielsdrost** [ESGF/esgf-pyclient#21]
esgf-pyclient is used in ESMValTool. We normally install packages via Conda (see the environment.yml file here: https://github.com/ESMValGroup/ESMValTool/blob/REFACTORING_backend/environment.yml

Would it be possible to create a Conda package for esgf-pyclient?

**Comment by cehbrecht** [comment]
@nielsdrost 
there is already a conda package on conda-forge (Python 2.7 only):

https://anaconda.org/conda-forge/esgf-pyclient

Probably It could be updated (10 month old) and I suppose Python 3.x should be supported.

**Comment by nielsdrost** [comment]
Great, thanks! Yes, Python 3 support would help, but would need #10 to be fixed first.

**Comment by agstephens** [comment]
@cehbrecht and @nielsdrost: I have put a Pull-Request in to conda-forge to update to v0.2.1.

**Comment by cehbrecht** [comment]
@nielsdrost the latest version of esgf-pyclient has made it now to conda-forge:
https://anaconda.org/conda-forge/esgf-pyclient
