### ISSUE TITLE
MyProxyClient integration: response change to bytes causing issues

### ISSUE THREAD

**Issue by agstephens** [ESGF/esgf-pyclient#24]
@philipkershaw: I've been testing the latest pyclient with Python 3 and I'm getting the following error from the `test_logon.py` tests:

```
       c = MyProxyClient(hostname=hostname, caCertDir=self.esgf_certs_dir)

        creds = c.logon(username, password,
                        bootstrap=bootstrap,
                        updateTrustRoots=update_trustroots)
        with open(self.esgf_credentials, 'w') as fh:
            for cred in creds:
>               fh.write(cred)
E               TypeError: write() argument must be str, not bytes

```

It looks like there has been a change in MyProxyClient returning bytes rather than a string. I tried a simple `fh.write(str(cred))` to fix it but it didn't work. Any idea what might fix this.

NOTE: Seems to work fine with python2.7.

**Comment by philipkershaw** [comment]
Try opening the file as write binary `open(self.esgf_credentials, 'wb')` - should fix it :)

**Comment by agstephens** [comment]
Thanks @philipkershaw . That's fixed it for both py2.7 and py3. 👍

**Comment by agstephens** [comment]
Fixed by using mode `wb`. Thanks @philipkershaw
