### ISSUE TITLE
Should Attribute Service calls work?

### ISSUE THREAD

**Issue by agstephens** [ESGF/esgf-pyclient#25]
Hi @philipkershaw, another question for you.

We have a call to the Attribute Service as defined in these tests:

```
class TestATS(TestCase):
    @pytest.mark.xfail(reason='This test does not work anymore.')
    def test_ceda_ats(self):
        service = AttributeService(CEDA_NODE.ats_url, 'esgf-pyclient')
        fn, ln = 'Ag', 'Stephens'
        resp = service.send_request(OPENID, ['urn:esg:first:name',
                                             'urn:esg:last:name'])

        assert resp.get_subject() == OPENID

        attrs = resp.get_attributes()
        assert attrs['urn:esg:first:name'] == fn
        assert attrs['urn:esg:last:name'] == ln

    @pytest.mark.xfail(reason='This test does not work anymore.')
    def test_multi_attribute(self):
        service = AttributeService(CEDA_NODE.ats_url, 'esgf-pyclient')

        resp = service.send_request(OPENID, ['CMIP5 Research'])

        attrs = resp.get_attributes()
        assert list(sorted(attrs['CMIP5 Research'])) == ['default', 'user']
```

Both tests fail at present. Do you know if this is because something has changed in the attribute service or whether there is just a configuration problem? These tests live in:

https://github.com/ESGF/esgf-pyclient/blob/master/pyesgf/test/test_ats.py

**Comment by philipkershaw** [comment]
This is calling the default ESGF attribute service location but we have this disabled in order to use our own, but our own is also being upgraded so there's no service available at all at the moment :/  You should be able to test against PCMDI's if needed

**Comment by agstephens** [comment]
Fixed by pointing to PCMDI node.
