### ISSUE TITLE
Logon Help

### ISSUE THREAD

**Issue by mattben** [ESGF/esgf-pyclient#3]
@agstephens and anyone else that sees this. Can I get some help getting the logonManager to work again. I'm getting

```
OpenSSL.SSL.Error: [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]
```

heres are the steps for recreating

```
cd esgf-pyclient
virtualenv env
source env/bin/activate
pip install MyProxyClient
python setup.py install
```

I removed my `~/.esg` and then went to pcmdi9 logged in search and clicked a wget, and ran it. which generated a new clean `~/.esg` directory    

I wrote a simple example test-log-on.py from the example given

```
import pyesgf.logon
lm = pyesgf.logon.LogonManager()
lm.logoff()
lm.is_logged_on()
lm.logon_with_openid('https://pcmdi9.llnl.gov/esgf-idp/openid/mattben', 'PassWord')
lm.is_logged_on() 
```

this is the output

```
(env)harris112@harris112ml1:[esgf-pyclient]:[master]:[15979]> python test-log-on.py 
Traceback (most recent call last):
  File "test-log-on.py", line 8, in <module>
    lm.logon_with_openid('https://pcmdi9.llnl.gov/esgf-idp/openid/mattben', '1Lakehole!')
  File "/Users/harris112/projects/ESGF/esgf-pyclient/pyesgf/logon.py", line 140, in logon_with_openid
    interactive=interactive)
  File "/Users/harris112/projects/ESGF/esgf-pyclient/pyesgf/logon.py", line 176, in logon     bootstrap=bootstrap, updateTrustRoots=update_trustroots)
      File "/Users/harris112/projects/ESGF/esgf-pyclient/env/lib/python2.7/site-ackages/myproxy/client.py", line 1412, in logon
**getTrustRootsKw)
  File "/Users/harris112/projects/ESGF/esgf-pyclient/env/lib/python2.7/site-packages/myproxy/client.py", line 1564, in getTrustRoots
conn.write('0')
  File "/Users/harris112/projects/ESGF/esgf-pyclient/env/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1271, in send
self._raise_ssl_error(self._ssl, result)
  File "/Users/harris112/projects/ESGF/esgf-pyclient/env/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1187, in _raise_ssl_error
_raise_current_error()
  File "/Users/harris112/projects/ESGF/esgf-pyclient/env/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]
```

Am I missing something? Any Help would be appreciated.

Sorry for the spamming: @LucaCinquini @ncaripsl @Prashanth Dwarakanath @philipkershaw @ sashakames

**Comment by agstephens** [comment]
Hi @mattben, The main developer of this code has moved on and we discussed whether the "logon.py" module should be deprecated as it is not fully tested. I will discuss with @philipkershaw and get back to you. A better solution might be to use other libraries to handle the authentication. Kind regards, Ag @agstephens

**Comment by mattben** [comment]
@agstephens @philipkershaw since @stephenpascoe has moved on, is it safe to say you two are the new maintainers? Instead of deprecating, can we/I fix it? I love this package and would like to see it grow.  A lot of my sites i'm working on are Django web apps and having a working esgf-pyclient makes life much easier. Not to be noise or pushy, is there a working group for this repo? If not we could start one? Also maybe instead of having a fork we should ask to move the repo to give us full access and/or just break ties. I'm not sure what the politics and issues would be with that its just an idea. In short I'd be glad to help out with this effort, also thank your for the quick responses.

**Comment by agstephens** [comment]
Hi @mattben,
I have discussed the issue with @philipkershaw and we are keen for you to help us with the development of esgf-pyclient. I have created a GitHub team and invited you into it. You should now have write access to the archive. Please follow the usual protocols of developing in your own branch and then asking me to merge in any changes from your branch when you have tested.
@philipkershaw is busy this week but will take a look at this issue when he gets a moment (unless you fix it before he gets there). Let me know if you have any problems getting access.
Thanks, @ESGF/esgf-pyclient-team

**Comment by mattben** [comment]
Thanks @agstephens I'd be very happy to contribute and will conform to the normal github policy of using PRs. Sorry i broke that rule a few days a go, updating the .gitignore file. 

to this issues, looks like the curllib does not support ssl context and i'm looking in to using httplib with ssl, more to come.

**Comment by mattben** [comment]
I am able to make the package work, with out any code changes. I'd like to recommended updating the docs. http://esgf-pyclient.readthedocs.org/en/latest I'm embarrassed to admit the SSL error was due to a Python version issues. I'm running python 2.7.5/6 on most servers. SSL was updated in python 2.7.9 for SSL Context https://docs.python.org/2/library/ssl.html?highlight=ssl.sslcontext#ssl.SSLContext `New in version 2.7.9.`. I wrote a basic Test and it works now. The process was:
1. Upgrade Python (I went to the newest 2.7.11)
2. Setup and Install requirements
   
   ```
   virtualenv env
   source env/bin/activate
   python --verson
   >> 2.7.11
   pip install esgf-pyclient MyProxyClient
   ```
3. The Simple Test Script
   
   ```
   import pyesgf.logon
   from local_settings import * # open_id and password
   oid = open_id
   pw = password
   lm = pyesgf.logon.LogonManager()
   lm.logoff()
   print lm.is_logged_on()
   lm.logon_with_openid(oid, pw)
   print lm.is_logged_on()
   ```
4. Run Test
   
   ```
   python logon_test.py
   >> False
   >> True
   ```

Thank you for your willingness to help and answer my questions, sorry to start a fuss about nothing. I'll continue to test logon and implement it in to my project.

**Comment by agstephens** [comment]
Hi Matthew,

Thanks for working out the issue. I will update the documentation to state this requirement when working with the LogonManager.

Thanks,
Ag

**Comment by agstephens** [comment]
Hi Matthew,

I've added a warning in the docs here:

http://esgf-pyclient.readthedocs.org/en/latest/logon.html

Thanks,
Ag

**Comment by philipkershaw** [comment]
Hi Matthew,

Glad to hear that you got to the bottom of this and sorry I wasn’t able to reply sooner.

Regarding SSL dependencies, MyProxyClient uses PyOpenSSL for SSL functionality so I would expect the issues you were seeing could be due to a stale version of PyOpenSSL or MyProxyClient. - Earlier versions of MyProxyClient used SSLv3 but it now uses TLS.  If your MyProxy server was rejecting SSLv3 (it should!) then it could cause an error like you were seeing.

Can you send me a full pip freeze output for the configuration that was failing?

Cheers,
Phil

**Comment by mattben** [comment]
@philipkershaw I think  you 100% correct i've tested around on on a few different versions of python and the issue was either no MyProxyClient installed or and older version.

the only failing output from pip I have shows that MyProxyClient is not installed.

```
> pip list 
esgf-pyclient (0.1.4b)
Jinja2 (2.8) 
MarkupSafe (0.23)
pip (1.5.6)
setuptools (3.6)
```

Again sorry for the false alarm.

**Comment by saeedvzf** [comment]
Would you please help me with this error?

from pyesgf.logon import LogonManager

KeyError                                  Traceback (most recent call last)
<ipython-input-12-f495fead8c53> in <module>
----> 1 from pyesgf.logon import LogonManager

D:\Anaconda\lib\site-packages\pyesgf\logon.py in <module>
     56 # Constants
     57 
---> 58 ESGF_DIR = op.join(os.environ['HOME'], '.esg')
     59 ESGF_CERTS_DIR = 'certificates'
     60 ESGF_CREDENTIALS = 'credentials.pem'

D:\Anaconda\lib\os.py in __getitem__(self, key)
    673         except KeyError:
    674             # raise KeyError with the original key value
--> 675             raise KeyError(key) from None
    676         return self.decodevalue(value)
    677 

KeyError: 'HOME'
