### ISSUE TITLE
Python3 compatibility in wget scripts

### ISSUE THREAD

**Issue by Zeitsperre** [ESGF/esgf-pyclient#31]
Hi all,

Thanks for maintaining this library. Really useful in my day to day. I wanted to raise an issue since I don't think Python3 is 100% compatible yet. When generating a `wget` script, I can only run it from my shell if my native Python is 2.7. This is a bit of pain when working in conda and needing to create a Python2.7 environment to run scripts written using Python3. 

The error raised when running the generated wget scripts with Python3 is as follows:
```
File "<stdin>", line 18
    print "-s %s -p %s -l %s" % (host, port, username)
                            ^
SyntaxError: invalid syntax
```

Is this a known issue? Are there plans to address this issue? Is this user error? Please let me know.

Cheers,

**Comment by cehbrecht** [comment]
@Zeitsperre The master is Python 3 only ... I have updated the examples and they are available as notebooks:
https://esgf-pyclient.readthedocs.io/en/latest/examples.html

**Comment by cehbrecht** [comment]
@Zeitsperre I consider this as "done". Please add a note when there are still issues.
