### ISSUE TITLE
Batch downloading >1000 files

### ISSUE THREAD

**Issue by Zeitsperre** [ESGF/esgf-pyclient#32]
Hi,

I'm wondering if there is a supported method for downloading files in batch numbers greater than 1000 using this tool. I'm running into an issue where if the script exceeds 1000, I cannot download the entire set. For example:
```
Warning! The total number of files was 3222 but this script will only process 1000.
Script created for 1000 file(s)
(The count won't match if you manually edit this file!)
```

I would like to know if there's a way of either increasing this limit or creating multiple wget scripts that can then be run in succession.

**Comment by Zeitsperre** [comment]
@cehbrecht ?

**Comment by cehbrecht** [comment]
@Zeitsperre I think the limit 1000 is on the server side. `esgf-pyclient` has no download method but you iterate about the searched datasets (unlimited) and run a download script (wget with certificate) on each found dataset.

As alternative you can also use synda:
http://prodiguer.github.io/synda/index.html

**Comment by Zeitsperre** [comment]
I stumbled across `synda` before and it looks promising. Thanks for the suggestion!
