### ISSUE TITLE
issue with  SHARD_REXP

### ISSUE THREAD

**Issue by paolap** [ESGF/esgf-pyclient#4]
Hi, 

I'm trying to use the module but every time I do a distributed search I bump into this error:

pyesgf.search.exceptions.EsgfSearchException: Shard spec esgf-node.jpl.nasa.gov/solr/datasets not recognised

SHARD_REXP = r'(?P<host>._?):(?P<port>\d_)/solr(?P<suffix>.*)'
changing this to
SHARD_REXP = r'(?P.?)(?P\d)/solr(?P.)'

in consts.py fixes it

Thanks,

Paola

**Comment by agstephens** [comment]
Hi @paolap,

Thanks for raising this. Does it work for all Solr end points when you make this change?

Ag

**Comment by paolap** [comment]
Hi,

I didn't have any issue with other end points after the change, but I couldn't be certain. I'm always doing distributed searches and they always work with the new regex

Paola

**Comment by agstephens** [comment]
Thanks @paolap, I'm taking a look. Ag

**Comment by agstephens** [comment]
Hi @paolap,

I think this is fixed now.

Please can you pull a copy of the "shard_regex" branch from the repository and check that it works for you.

https://github.com/ESGF/esgf-pyclient/tree/shard_regex

Please confirm it works and then I'll roll out a new version.

Thanks,

Ag

**Comment by paolap** [comment]
Hi Ag,

this is working for me now, thanks for looking into it so quickly

Thanks,

Paola

**Comment by jkettleb** [comment]
Hello @agstephens,

based on the testing I have done so far - this works for me too.  Thanks for looking at this.

Jamie

**Comment by agstephens** [comment]
@jkettleb and @paolap,

Thanks for testing. I'll roll out a new version.

Cheers,

Ag

**Comment by agstephens** [comment]
@jkettleb and @paolap,

Please see the latest release and the head of master for this fix:

 https://github.com/ESGF/esgf-pyclient/releases/tag/0.1.6

Cheers,

Ag
