### ISSUE TITLE
Remove unused code parts?

### ISSUE THREAD

**Issue by cehbrecht** [ESGF/esgf-pyclient#44]
Some code parts are never used or mentioned in the docs:
* `pyesgf/node.py`
* `pyesgf/manifest.py`
* `pyesgf/security/ats.py`

Should we remove them?

**Comment by agstephens** [comment]
@cehbrecht : please remove these. Thanks

**Comment by pchengi** [comment]
@agstephens , @cehbrecht , please don't remove ats.py. I have scripts that use pyesgf and query the attribute services, to figure out users' group membership status.

**Comment by pchengi** [comment]
@cehbrecht , looks fine. From commit e71354d1beecf1a81473412f56d3bb7d130099e1, I realize python 2.7 is no longer supported. I'll try with a python3 version of my script and get back to you soon. For the record, everything worked as expected with the current branch, when I changed the urllib to urllib2 in ats.py, under python2.7,  so everything else should be good.

**Comment by cehbrecht** [comment]
@pchengi Let me know when I can merge or if you like to have changes. If there issues not related to this PR, we can have a follow-up PR.

**Comment by pchengi** [comment]
@cehbrecht , should be totally fine to merge this. I'll follow up with a seperate PR, if needed, as you suggest.

**Comment by cehbrecht** [comment]
fixed by PR #49.
