### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by sannemuis** [ESGF/esgf-pyclient#47]
I get a SSL error when I try to log in with OPENID. It seems that there is a mismatch between OpenSSL versions between my environment and the LLNL node. Would you be able to tell me on version of pyopenssl ESGF Pyclient is built?

**Comment by cehbrecht** [comment]
@sannemuis You need the latest `myproxyclient` (2.1.0) which is not on conda-forge yet.

I tried it with the following installation:
```
$ conda create -c conda-forge -n esgf-pyclient python=3.6 pip esgf-pyclient
$ conda activate esgf-pyclient
(esgf-pyclient) pip install myproxyclient
```

**Comment by cehbrecht** [comment]
You need to use the `bootstrap=True` option on first logon, otherwise the following error may occur:
```
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
```

The following procedure worked:
```
conda create -c conda-forge -n esgf-pyclient python=3.6 pip esgf-pyclient
conda activate esgf-pyclient
(esgf-pyclient) pip install myproxyclient
(esgf-pyclient) python
import pyesgf.logon
lm = pyesgf.logon.LogonManager()
lm.logon(hostname='esgf-data.dkrz.de', interactive=True, bootstrap=True)
```
