### ISSUE TITLE
adding a download option

### ISSUE THREAD

**Issue by paolap** [ESGF/esgf-pyclient#5]
Hi Ag,

first of all I should say that I'm a data "expert" for a climate science centre in Australia and I've been using the esgf-pyclient embedding it into a python interface to our local collection at NCI. So our users can compare what's available locally to what is online to a fine detail. Claire Trenham from NCI forwarded to me an e-mail conversation from the esgf-devel mailing list regarding the need of a "search and download" tool. Both synda and pyesgf were mentioned, I've never used synda though I will have a go now, pyesgf was good for me because it gives a lot of details, which I found necessary to compare files when the version information is missing.
I'm really interested in any progress on this discussion. In fact, when I chose pyesgf I assumed I could use it to download the files too. I was surprised because it is taking care of the certificates with the logon function, you can extract very easily the files download urls and checksums,  but then there's no download option. I've actually tried to add one by myself, but I didn't have time to do it properly and I set it aside. Our python module was developed to fill a hole in the services we have (or better we don't have) available.
So if you decide to add this enhancement I'll be happy to be a tester. Though I'll be away for the next two months and back in mid-July.

Regards,

Paola

**Comment by nedclimaterisk** [comment]
Yes, this would be great. Paola, did you ever look any further into this? I will probably give it a go some time soon, as I find the wget scripts fairly clunky to work with (e.g. if you only need a subset of the files). I only just found this library though, so it might take me a little while to ramp up to it.

**Comment by paolap** [comment]
Hi,
we don't use this module anymore, in fact I might even close this issue since no one ever answered. Maybe you should try synda instead.
