### ISSUE TITLE
[Errno -77] NetCDF: Access failure

### ISSUE THREAD

**Issue by karimnorouzi** [ESGF/esgf-pyclient#50]
I dont know exactly what is wrong, but I am trying to use one of the examples and it does not work.
Here is the script the produces the result:

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
#############
from pyesgf.logon import LogonManager
lm = LogonManager()
lm.logoff()
lm.is_logged_on()
password = '******'
openId = 'https://esgf-data.dkrz.de/esgf-idp/openid/********'
lm.logon_with_openid(openId, password, bootstrap=True)
lm.is_logged_on()

import xarray as xr
url = 'http://esgf2.dkrz.de/thredds/fileServer/lta_dataroot/cmip5/output1/MIROC/MIROC5/rcp45/mon/aerosol/aero/r1i1p1/v20120514/wetss/wetss_aero_MIROC5_rcp45_r1i1p1_200601-210012.nc'
ds = xr.open_dataset(url , chunks={'time': 120})
print(ds)

**Comment by cehbrecht** [comment]
The download access works only for OpenDAP. In this case it is file-access:
http://esgf2.dkrz.de/thredds/fileServer/

The esgf2.dkrz.de data node provides only replicas from the DKRZ archive. The node has only file-access. Please use the original dataset.

**Comment by karimnorouzi** [comment]
Could you please kindly elaborate. 
I use the following code to search for the files, the urls are returned by the search process:

```
from pyesgf.search import SearchConnection
# conn = SearchConnection('https://esgf-data.dkrz.de/esg-search',  distrib=True)
ctx = conn.new_context(
    project='CORDEX',
    variable = ['pr', 'tas'],
    time_frequency=['3hr'], # '6hr'],
    domain = 'NAM-22',
    )
ctx.hit_count
rslts = ctx.search()
urls = []
for r in rslts:
    files = r.file_context().search()
    for file in files:
        if file.opendap_url is not None:
            urls.append(file.opendap_url)
            print('adding {}'.format(file.opendap_url))


```

Should I replace esgf2 with esgf at the url ? 
The funny thing is that I can download the files using the wget script. It works. But not with my pyclient program. It must be something I am doing wrong.
thanks.

**Comment by cehbrecht** [comment]
@karimnorouzi I tried your search and it returns files from datanode esgf1, like:
http://esgf1.dkrz.de/thredds/dodsC/cordex/cordex/output/NAM-22/GERICS/MOHC-HadGEM2-ES/historical/r1i1p1/GERICS-REMO2015/v1/3hr/tas/v20191015/tas_NAM-22_MOHC-HadGEM2-ES_historical_r1i1p1_GERICS-REMO2015_v1_3hr_197001010100-197012302200.nc

Currently it looks like the group registration service for CORDEX at SMHI is not responding.
@pchengi2 Could you please check?

**Comment by alaniwi** [comment]
It works with 
```
url2 = url.replace("fileServer", "dodsC")
ds = xr.open_dataset(url2 , chunks={'time': 120})
```

**Comment by alaniwi** [comment]
Cannot reproduce the problem with search. The search correctly sets the relevant URLs.

Example:
```
>>> file.download_url
'http://esgf1.dkrz.de/thredds/fileServer/cordex/cordex/output/NAM-22/GERICS/MPI-M-MPI-ESM-LR/historical/r1i1p1/GERICS-REMO2015/v1/3hr/tas/v20191015/tas_NAM-22_MPI-M-MPI-ESM-LR_historical_r1i1p1_GERICS-REMO2015_v1_3hr_200501010100-200512312200.nc'
>>> file.opendap_url
'http://esgf1.dkrz.de/thredds/dodsC/cordex/cordex/output/NAM-22/GERICS/MPI-M-MPI-ESM-LR/historical/r1i1p1/GERICS-REMO2015/v1/3hr/tas/v20191015/tas_NAM-22_MPI-M-MPI-ESM-LR_historical_r1i1p1_GERICS-REMO2015_v1_3hr_200501010100-200512312200.nc'
>>> file.gridftp_url
'gsiftp://esgf1.dkrz.de:2811//cordex/cordex/output/NAM-22/GERICS/MPI-M-MPI-ESM-LR/historical/r1i1p1/GERICS-REMO2015/v1/3hr/tas/v20191015/tas_NAM-22_MPI-M-MPI-ESM-LR_historical_r1i1p1_GERICS-REMO2015_v1_3hr_200501010100-200512312200.nc'
```

The URL hard coded in the script at the top is a download URL.

**Comment by saeedvzf** [comment]
anyone here can help me with this error?

from pyesgf.logon import LogonManager
lm = LogonManager()
lm.logoff()
lm.is_logged_on()

KeyError                                  Traceback (most recent call last)
<ipython-input-10-be218eb9eb90> in <module>
----> 1 from pyesgf.logon import LogonManager
      2 lm = LogonManager()
      3 lm.logoff()
      4 lm.is_logged_on()
      5 

D:\Anaconda\lib\site-packages\pyesgf\logon.py in <module>
     56 # Constants
     57 
---> 58 ESGF_DIR = op.join(os.environ['HOME'], '.esg')
     59 ESGF_CERTS_DIR = 'certificates'
     60 ESGF_CREDENTIALS = 'credentials.pem'

D:\Anaconda\lib\os.py in __getitem__(self, key)
    679         except KeyError:
    680             # raise KeyError with the original key value
--> 681             raise KeyError(key) from None
    682         return self.decodevalue(value)
    683 

KeyError: 'HOME'

I did everything but still it comes with an error!

Also, How should I search, and which address I should put in search to retrieve all the results? Because for example when I search with conn = SearchConnection('http://esgf-data.dkrz.de/esg-search', distrib=False) 
It only finds several hints and can not capture all the results. 

I have an openID with user and pass and prefer to search on CEDA!

Thank you
