### ISSUE TITLE
Trouble on to_netcdf()

### ISSUE THREAD

**Issue by denisefukai** [ESGF/esgf-pyclient#56]
Hi there,

I'm currently trying to download subsets of some CMIP6 models data using the esgf-pyclient following the [https://esgf-pyclient.readthedocs.io/en/latest/notebooks/demo/subset-cmip6.html
] examples. It works mostly great, two minors adjustments I had to make were setting 'decode_cf' to 'False' while opening xr, and spatial subsetting (da.sel() doesn't work probably because my data has multidimensional coordinates but manage to get a workaround on it). 

However, once I get to the point to extract it to .nc, a simple da.to_netcdf('test.nc') returns me an "AttributeError: NetCDF: String match to name in use" error. I've tried then setting up to netcdf3_classic (as a test)

>> da.to_netcdf('teste.nc', 'w', 'NETCDF3_CLASSIC')

and it does initially run, creates a file but it breaks down at some point witch don’t surprise me much as netcdf3_classic is not well prepared to handle files over 2GB. Then I get the errors:
...
RuntimeError: NetCDF: Operation not allowed in define mode...  During handling of the above exception, another exception occurred: ..... RuntimeError: NetCDF: One or more variable sizes violate format constraints.

Opening the created file makes no sense as the variable of interest comes up full of '--' (nothing just which seems '-' strings but it takes up over 2GB of no data). I've tried too with files I know are under 2GB just as a test and the error I get is "RuntimeError: NetCDF: Access failure" (when using to_netcdf, they are also created but make no sense).

I've looked up through the data before setting up to extract to nc. I'm still learning programming, python and handling netcdf files but I manage to understand a bit. Using dask and data access protocols such as opendap(pydap/netcdf4) however, it's still a bit cloudy for me. I was able to access the references variables values (time, lat, lon, levels) but once I get to my variable of interest values, it just also breaks down, examples below: 

>> vo = da.variables["vo"][:,:,:,:].values # RuntimeError: NetCDF: Access failure
>> vo = subset.variables['vo'][1,1,:,:].values # it does work, but I'm then able to access all the values of my variable to construct my whole file

I should note if I don't set the decode_cf to False, the error while trying to create the nc is "AttributeError: 'numpy.float64' object has no attribute ‘year’ (just in case someone runs into it too).

Any thoughts?

**Comment by cehbrecht** [comment]
@denisefukai did the example notebook work for you? Do you have a pointer to the cmip6 file that does not work?

**Comment by denisefukai** [comment]
Hey @cehbrecht,
If I run the example as it shows, from beginning to end (including subsetting), it does run smoothly. However, try exporting "ds" instead of "da" in the example and you'll see it also breaks ("AttributeError: NetCDF: String match to name in use"), which I think it's something related to the amount of data being transferred and written in netcdf4.

My data is even heavier than the single-level used in the example, I can get the file specs for you if you want to... but would be a good idea to have a go exporting the whole dataset from the example first, so we see if you get the same error I get here.

**Comment by agstephens** [comment]
@denisefukai : I have reviewed this issue on the esgf-pyclient repository. I believe the issue to be related to the structure of the netCDF file rather than the functionality of the esgf-pyclient code itself. I am closing this issue. Let me know if my interpretation is incorrect and we can take another look.
