### ISSUE TITLE
openssl.ssl.error ('ssl routines' 'ssl3_get_record' 'wrong version number')

### ISSUE THREAD

**Issue by andreall** [ESGF/esgf-pyclient#57]
I am running a download script using openid for CORDEX data. It is a script that I have been using successfully on different computers (windows, masosx and linux). I am trying to use it in other computers with first_time=True:
`lm = LogonManager()`
`lm.logon_with_openid(openid=openid, password=password, bootstrap=first_time)` 

and the error:
File "/home/lloarca/climate_change/cordex/download.py", line 42, in search
    lm.logon_with_openid(openid=openid, password=password, bootstrap=first_time)
  File "/opt/anaconda3/lib/python3.7/site-packages/pyesgf/logon.py", line 149, in logon_with_openid
    interactive=interactive)
  File "/opt/anaconda3/lib/python3.7/site-packages/pyesgf/logon.py", line 185, in logon
    updateTrustRoots=update_trustroots)
  File "/opt/anaconda3/lib/python3.7/site-packages/myproxy/client.py", line 1448, in logon
    **getTrustRootsKw)
  File "/opt/anaconda3/lib/python3.7/site-packages/myproxy/client.py", line 1605, in getTrustRoots
    conn.write(self.__class__.GLOBUS_INIT_MSG)
  File "/opt/anaconda3/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1757, in send
    self._raise_ssl_error(self._ssl, result)
  File "/opt/anaconda3/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "/opt/anaconda3/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_get_record', 'wrong version number')]

I have openssl version 1.0.1k on one of them and 1.1.0i on another one. On both I get the same error. Any thoughts?

**Comment by ConorIA** [comment]
It seems the ESGF uses old (deprecated) encryption on the server side. See: https://github.com/cedadev/MyProxyClient/issues/14

This did the trick for me, though I am not sure if I needed all the imports: 

```python
from pyesgf.logon import LogonManager
from myproxy.client import MyProxyClient
from OpenSSL import SSL
MyProxyClient.SSL_METHOD = SSL.TLSv1_2_METHOD

lm = LogonManager()
lm.logon_with_openid(openid, password=password)
```

**Comment by agstephens** [comment]
@alaniwi : please put a note here related to PK comments in other repos.

**Comment by bouweandela** [comment]
I'm encountering this issue when trying to connect to `esgf-data.dkrz.de`, with a fresh installation of esgf-pyclient from conda:
```
$ conda env export
name: esgf-pyclient
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2021.10.8=ha878542_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - esgf-pyclient=0.3.1=pyh6c4a22f_0
  - idna=3.3=pyhd8ed1ab_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_12
  - libgomp=11.2.0=h1d223b6_12
  - libnsl=2.0.0=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.11=h36c2ea0_1013
  - myproxyclient=2.1.0=pyhd8ed1ab_2
  - ncurses=6.3=h9c3ff4c_0
  - openssl=1.1.1l=h7f98852_0
  - pip=22.0.3=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - python=3.10.2=h85951f9_3_cpython
  - python_abi=3.10=2_cp310
  - readline=8.1=h46c0cb4_0
  - requests=2.27.1=pyhd8ed1ab_0
  - requests_cache=0.4.13=py_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=h9cd32fc_0
  - tk=8.6.12=h27826a3_0
  - tzdata=2021e=he74cb21_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - webob=1.8.7=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h36c2ea0_1013
  - pip:
    - brotlipy==0.7.0
    - certifi==2021.10.8
    - cffi==1.15.0
    - cryptography==36.0.1
    - markupsafe==2.1.0
    - pysocks==1.7.1
    - setuptools==60.9.3
prefix: /home/bandela/mambaforge/envs/esgf-pyclient
```
@cehbrecht @agstephens Do you have any idea what could be going on?

I'm able to logon to `slcs.ceda.ac.uk` just fine, so it looks like a problem specific to the DKRZ.

**Comment by cehbrecht** [comment]
I have tried the logon using this notebook:
https://github.com/ESGF/esgf-pyclient/blob/master/notebooks/examples/logon.ipynb

It worked for me for the IPSL node. But I got a "connection refused" error from the DKRZ node.

@soay do you have some hints?

I tried it also with the "trick" mentioned above ... but failed also:
```python
from pyesgf.logon import LogonManager
from myproxy.client import MyProxyClient
from OpenSSL import SSL
MyProxyClient.SSL_METHOD = SSL.TLSv1_2_METHOD
```


The search is still working:
https://github.com/ESGF/esgf-pyclient/blob/master/notebooks/examples/search.ipynb

**Comment by soay** [comment]
Our MyProxy Server is not working at the moment. I am waiting for a fresh certificate. I hope Prashanth can sign this soon.

**Comment by soay** [comment]
MyProxy@DKRZ should be working again.

**Comment by cehbrecht** [comment]
I tried again ... I don't get a connect error now ... but the logon is hanging ...

**Comment by cehbrecht** [comment]
@bouweandela checked it again with @soay. Locally on my mac the logon works ... even for Python 3.10. But on binder it is running into a timeout. Might be an issues with the binder configuration?
https://nbviewer.org/github/ESGF/esgf-pyclient/blob/master/notebooks/examples/logon.ipynb

**Comment by bouweandela** [comment]
Thanks for looking into this @cehbrecht and @soay! It works fine on my laptop too now. Maybe we can close this issue? I think the original problem has been solved a long time ago in https://github.com/cedadev/MyProxyClient/issues/14 and https://github.com/cedadev/MyProxyClient/commit/ab8da41f1e1caf18007bf9a4f7321999dff375b2.
