### ISSUE TITLE
batch_size setting alters the number of results returned by search

### ISSUE THREAD

**Issue by EmmaHibling** [ESGF/esgf-pyclient#59]
I've found an example of a search using pyesgf where changing the batch size changes the number of results although the documentation says: "The batch_size argument does not affect the final result but may affect the speed of the response."

Here's a test that demonstrates the problem:

    import unittest

    from pyesgf.search import SearchConnection

    class TestBatchSize(unittest.TestCase):

        def test_batch_size_has_no_impact_on_results(self):
            conn = SearchConnection(
                'https://esgf-index1.ceda.ac.uk/esg-search', distrib=True)
            ctx = conn.new_context(
                mip_era='CMIP6', institution_id='CCCma', 
                experiment_id='pdSST-pdSIC', table_id='Amon', variable_id='ua')
            results = ctx.search(batch_size=50)
            ids_batch_size_50 = sorted(results, key=lambda x: x.dataset_id)

            ctx = conn.new_context(
                mip_era='CMIP6', institution_id='CCCma', 
                experiment_id='pdSST-pdSIC', table_id='Amon', variable_id='ua')
            results = ctx.search(batch_size=100)
            ids_batch_size_100 = sorted(results, key=lambda x: x.dataset_id)

            self.assertEqual(len(ids_batch_size_50), len(ids_batch_size_100))

    if __name__ == '__main__':
        unittest.main()

**Comment by cehbrecht** [comment]
@EmmaHibling I have added your test in PR #66. The test currently works. So I'm closing. But please open it again if it is still an issue.
