### ISSUE TITLE
Latest release (v0.2.2) missing from PyPI and conda forge

### ISSUE THREAD

**Issue by bouweandela** [ESGF/esgf-pyclient#62]
It looks like the latest release (v0.2.2) is not available on PyPI and conda forge. Is there a reason for this or did you forget to upload it?

**Comment by cehbrecht** [comment]
@agstephens Can you add me to the maintainers on pypi:
https://pypi.org/project/esgf-pyclient/

I can upload the 0.2.2 version just for reference and to check the conda-forge pipeline. We can then make a 0.3 release.

**Comment by agstephens** [comment]
@cehbrecht what is your username on pypi?

**Comment by cehbrecht** [comment]
> @cehbrecht what is your username on pypi?

pingucarsti

**Comment by agstephens** [comment]
@cehbrecht I have added you.

**Comment by cehbrecht** [comment]
@bouweandela version 0.2.2 is now on pypi and conda-forge. There will be a new release 0.3.0 in the next days for the current version.

**Comment by bouweandela** [comment]
Thanks!
