### ISSUE TITLE
Error with requests_cache dependency

### ISSUE THREAD

**Issue by agstephens** [ESGF/esgf-pyclient#71]
Mark at the MO reported this error when running this code:

```
from pyesgf.search import SearchConnection
conn = SearchConnection('http://esgf-index1.ceda.ac.uk/esg-search', distrib=True)

ctx = conn.new_context(project='CMIP5', query='humidity')
ctx.hit_count
```

Error:

```
/usr/local/lib/python3.7/dist-packages/pyesgf/search/connection.py in
open(self)
     96     def open(self):
     97         if (isinstance(self._passed_session, requests.Session)
or isinstance(
---> 98                 self._passed_session,
requests_cache.core.CachedSession)):
     99             self.session = self._passed_session
    100         else:

AttributeError: module 'requests_cache' has no attribute 'core'

```

A quick search suggests that the API inside the package has changed. 

An older version worked fine:

`requests_cache-0.4.1`

The new version that failed was:

`requests_cache-0.6.4`

Needs further investigation.

**Comment by agstephens** [comment]
Versions of `requests_cache` when current `esgf-pyclient` works: 0.5.2
Versions of `requests_cache` when we get this error: >=0.6.0

**Comment by JWCook** [comment]
The reference to `requests_cache.core.CachedSession` just needs to be changed to `requests_cache.CachedSession`.

**Comment by agstephens** [comment]
Thanks @JWCook 
I have checked this works all the way back to version 0.4.13 of `requests_cache` (as packaged in conda-forge) - so it should be fine to make the change.

**Comment by agstephens** [comment]
@alaniwi here is one for you to look at next week (when I'm on leave).

**Comment by alaniwi** [comment]
The updates to the library API have already been made at a41c5248682ef7702c7e4d74bf13d952d709f080 which is in master.

Tests are passing with this change (for more details see #72). 

Closing.
