### ISSUE TITLE
Dependency problem (version mismatch between pyesgf and requests library) leading to AttributeError: module 'requests_cache' has no attribute 'core'

### ISSUE THREAD

**Issue by merretbuurman** [ESGF/esgf-pyclient#78]
Hi!
I pip installed pyesgf and also requests, but apparently the versions don't work well together. apparently pyesgf (0.3.0) needs a different version of requests than the one currently available on pip.

I tried this:

```
myinstance = 'CMIP6.AerChemMIP.BCC.BCC-ESM1.ssp370SST-lowNTCF.r1i1p1f1.Lmon.tsl.gn.v20190612'
conn = SearchConnection(index_search_url, distrib=False)
ctx = conn.new_context(project="CMIP6", instance_id=myinstance)
dset=ctx.search()

files=dset.file_context().search()
i=0
for file in files:
    i += 1
    print('%s : %s' % (i, file.json["instance_id"]))

```

And run into this error:

```
Traceback (most recent call last):
  File "corr.py", line 21, in <module>
    dset=ctx.search()
  File "/home/.../venv3/lib/python3.6/site-packages/pyesgf/search/context.py", line 126, in search
    sc.__update_counts(ignore_facet_check=ignore_facet_check)
  File "/home/.../venv3/lib/python3.6/site-packages/pyesgf/search/context.py", line 206, in __update_counts
    response = self.connection.send_search(query_dict, limit=0)
  File "/home/.../venv3/lib/python3.6/site-packages/pyesgf/search/connection.py", line 156, in send_search
    self.open()
  File "/home/.../venv3/lib/python3.6/site-packages/pyesgf/search/connection.py", line 98, in open
    self._passed_session, requests_cache.core.CachedSession)):
AttributeError: module 'requests_cache' has no attribute 'core'
```

Versions/environment:

```
Python 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyesgf
>>> import requests
>>> requests.__version__
'2.26.0'
>>> pyesgf.__version__
'0.3.0'
>>> 
```

If you need any more details, don't hesitate to contact me (or also @cehbrecht ). Thanks!

**Comment by cehbrecht** [comment]
I can reproduce this issue with `pip install esgf-pyclient`. It doesn't like a newer version of `requests_cache`. It still works with:
```
pip install requests_cache==0.5 
```

**Comment by cehbrecht** [comment]
This was already fixed on `master`. See PR #68. 

To install the latest master version:
```
pip install git+https://github.com/ESGF/esgf-pyclient.git 
```

We need a patch release of esgf-pyclient.

**Comment by cehbrecht** [comment]
@alaniwi could we make a new release and upload to pypi?

**Comment by bouweandela** [comment]
A new release has been made #82 and this issue should be now be solved. @merretbuurman Is your problem solved with the latest release?

**Comment by valeriupredoi** [comment]
#95 adds a conda-forge environment with all deps installed from there, these conflicts should not appear in this context anymore - I've not seen it myself, and I'll eat my hat if it happens again :tophat: :grin: Closing this, please reopen if still a problem
