### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by bouweandela** [ESGF/esgf-pyclient#81]
Would it be possible to make a new release? @agstephens or @cehbrecht? Our users are complaining that search is slow https://github.com/ESMValGroup/ESMValCore/issues/1495. I think that now that #75 has been fixed, we could speed up our search by almost a factor of 2.

**Comment by cehbrecht** [comment]
I will prepare a PR for the release ...

**Comment by agstephens** [comment]
@cehbrecht the new release looks good. Do you need any further review from me, or can we close this issue?

**Comment by bouweandela** [comment]
Thanks @cehbrecht!

**Comment by cehbrecht** [comment]
@agstephens looks like all worked ... including the conda package :)

**Comment by agstephens** [comment]
Great stuff @cehbrecht. Thanks!
