### ISSUE TITLE
logon refused from my laptop

### ISSUE THREAD

**Issue by wu841227** [ESGF/esgf-pyclient#92]
Hello, 

I am trying to logon to ESGF with pyclient from my macOS with Python 3.10.10.
However, I got the error of "connection refused" when I try the example logon code with either openID or username and password.
The error message is as following:

 File "/Users/lwu/mambaforge/envs/esmvaltool/lib/python3.10/site-packages/pyesgf/logon.py", line 184, in logon
    creds = c.logon(username, password,
  File "/Users/lwu/mambaforge/envs/esmvaltool/lib/python3.10/site-packages/myproxy/client/__init__.py", line 1453, in logon
    self.getTrustRoots(writeToCACertDir=True,
  File "/Users/lwu/mambaforge/envs/esmvaltool/lib/python3.10/site-packages/myproxy/client/__init__.py", line 1609, in getTrustRoots
    conn.connect((self.hostname, self.port))
  File "/Users/lwu/mambaforge/envs/esmvaltool/lib/python3.10/site-packages/OpenSSL/SSL.py", line 2105, in connect
    return self._socket.connect(addr)
ConnectionRefusedError: [Errno 61] Connection refused

**Comment by bouweandela** [comment]
It seems likely that there is an issue with connecting from your laptop to your OpenID provider. This issue may be unrelated to the esgf-pyclient software package.

You could have a look at the [ESGF user guide on logging in](https://esgf.github.io/esgf-user-support/user_guide.html#login-openid) and their [FAQ](https://esgf.github.io/esgf-user-support/faq.html#esgf-login-registration). If you still encounter problems, I would recommend asking for help on the [ESGF users mailing list](https://esgf.github.io/esgf-user-support/faq.html#how-to-contact-us).

**Comment by wu841227** [comment]
Hello bouweandela,

I don't think the problem is due to the connection between my laptop and OpenID provider. Because I also tried wget option to download data from my laptop. For wget, I also need to provide OpenID and password and this works normally.

I suspect the error is due to the fact that OpenSSL service is NOT available from ESGF.
Because when I checked the connection with nmap command, I got following results:

> Starting Nmap 7.93 ( https://nmap.org ) at 2023-05-08 15:13 CEST
> Nmap scan report for esgf-node.llnl.gov (198.128.245.159)
> Host is up (0.0066s latency).
> Not shown: 990 closed tcp ports (conn-refused)
> PORT      STATE    SERVICE
> 21/tcp    filtered ftp
> 22/tcp    filtered ssh
> 53/tcp    filtered domain
> 80/tcp    open     http
> 443/tcp   open     https
> 8080/tcp  filtered http-proxy
> 8443/tcp  filtered https-alt
> 20000/tcp filtered dnp
> 20005/tcp filtered btx
> 20031/tcp filtered unknown

**Comment by valeriupredoi** [comment]
if this is still relevant, please do re-open, but I also suggest asking the ESGF as @bouweandela recommended; enabling OpenSSL types of connection this is not something we can do, it all depends how ESGF have configured their access :beer:
