### ISSUE TITLE
collection import errors from python 3.10

### ISSUE THREAD

**Issue by EmmaHibling** [ESGF/esgf-pyclient#94]
pyesgf module search/results.py and dependency webob.multidict both try to do deprecated imports from collection that break at python 3.10.

In results.py, the line:

`from collections import Sequence, defaultdict`

needs to be changed to:
```
from collections import defaultdict
from collections.abc import Sequence
```

and webob/multidict.py needs to have `from collections import MutableMapping` changed to:
```
from collections.abc import MutableMapping
```

**Comment by valeriupredoi** [comment]
many thanks @EmmaHibling :beer: I am closing this since the suggested code changes have been made (very possible that the issue was not closed when the relevant PR was merged) :+1:
